export const services = [
  { name: "Frisör" },
  { name: "Barberare" },
  { name: "Massage" },
  { name: "Hudvård" },
  { name: "Nagelsalong" },
  { name: "Makeup & Styling" },
  { name: "Fransar & Bryn" },
  { name: "Spa & Avkoppling" },
  { name: "Hårborttagning" },
  { name: "Sjukgymnastik" },
  { name: "Kiropraktor" },
  { name: "Akupunktur" },
  { name: "Zonterapi" },
  { name: "Tandblekning" },
  { name: "Personlig träning" },
  { name: "Kostrådgivning" },
  { name: "Manikyr & Pedikyr" },
  { name: "Ansiktsbehandling" },
  { name: "Botox & Fillers" },
  { name: "Alternativ medicin" },
];
