import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans';

import "./globals.css";
import ReactQueryProvider from "@/providers/tanstackProvider";
import { Toaster } from "@/components/ui/toaster";
import TheDashboardHeader from "@/components/header/TheDashboardHeader";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <ReactQueryProvider>
          <TheDashboardHeader />
          {children} <Toaster />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
